pull_request_rules:

  - name: label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: ["type: dependencies"]

  - name: label ovo-scala-steward's failed PRs
    conditions:
      - author=scala-steward
      - status-failure=ci
    actions:
      label:
        add:
          - scala-steward
          - failed-update

  - name: label scala-steward's major version PRs
    conditions:
      - author=scala-steward
      - body~=labels:.*early-semver-major
    actions:
      label:
        add:
          - scala-steward
          - major-update

  - name: automatically merge scala-steward's minor version PRs
    conditions:
      - author=scala-steward
      - "status-success=ci"
      - body~=labels:.*early-semver-minor
    actions:
      review:
        type: APPROVE
      merge:
        strict: smart
        strict_method: rebase
        method: merge
      label:
        add:
          - scala-steward
          - minor-update
        remove:
          - failed-update
      delete_head_branch: {}

  - name: automatically merge scala-steward's patch version PRs
    conditions:
      - author=ovo-scala-steward
      - "status-success=ci"
      - body~=labels:.*early-semver-patch
    actions:
      review:
        type: APPROVE
      merge:
        strict: smart
        strict_method: rebase
        method: merge
      label:
        add:
          - scala-steward
          - patch-update
        remove:
          - failed-update
      delete_head_branch: {}

  - name: automatic update for dependency update PRs
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - "label=type: dependencies"
    actions:
      update: {}
