pull_request_rules:
  - name: Automatically approve
    conditions:
      - author=ovo-scala-steward
      - check-success=snyk
      - check-success=unit-tests
    actions:
      review:
        type: APPROVE

  - name: Automatically merge
    conditions:
      - author=ovo-scala-steward
      - check-success=snyk
      - check-success=unit-tests
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
