name: ci

on:
  push:
    branches:
      - main
      - master
      - release/*
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith( github.ref, 'refs/heads/release/' ) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - run: sbt "+scalafmtCheckAll;+headerCheckAll;+compile;+Test/compile"
      - run: sbt "+Test/test"
      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          list-suites: "all"
          list-tests: "all"
          max-annotations: 10
          fail-on-error: true
          name: unit-tests-report
          path: "**/target/test-reports/*.xml"
          reporter: java-junit
      - uses: alehechka/upload-tartifact@v2
        with:
          name: targets
          path: "**/target/**"
          if-no-files-found: error
          retention-days: 1

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SET UP - Snyk
        uses: snyk/actions/scala@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high --fail-on=all

  publish:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' ||startsWith( github.ref, 'refs/heads/release/' ) # Only runs on releases
    runs-on: ubuntu-latest
    needs:
      - build
      - snyk
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - uses: alehechka/download-tartifact@v2
        with:
          name: targets
          path: .
      - run: git fetch --tags
      - run: git status
      - name: Bump version and push tag
        id: tag-version
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          TAG_CONTEXT: branch
      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag-version.outputs.new_tag }}
          name: ${{ steps.tag-version.outputs.new_version }}
          body: ${{ steps.tag-version.outputs.changelog }}
      - run: git fetch --tags
      - name: publish
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_KEY }}
        run: sbt +publish
