name: main

on:
  push:
    branches:
      - master
      - release/*
  pull_request:

concurrency:
  group: ${{ github.ref }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - run: sbt +update
      - uses: scalacenter/sbt-dependency-submission@v2

  build:
    runs-on: ubuntu-latest
    needs: update-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - run: sbt +scalafmtCheckAll
      - run: sbt +compile
      - name: Compress targets
        run: |
          shopt -s globstar
          tar -cvzf targets.tar.gz **/target/**
      - name: Upload targets
        uses: actions/upload-artifact@v3
        with:
          name: targets
          path: targets.tar.gz
          if-no-files-found: error
          retention-days: 1

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - name: Download targets
        uses: actions/download-artifact@v3
        with:
          name: targets
      - name: Expand targets
        run: tar -xvzf targets.tar.gz
      - run: sbt clean +test
      - name: Unit Test Report
        uses: dorny/test-reporter@v1.6.0
        # run this step even if previous step failed
        if: success() || failure()
        with:
          list-suites: "all"
          list-tests: "all"
          max-annotations: 10
          fail-on-error: true
          name: unit tests
          path: "**/target/test-reports/*.xml"
          reporter: java-junit

  snyk:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: SET UP - Snyk
        uses: snyk/actions/scala@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high --fail-on=all

  publish:
    if: github.ref == 'refs/heads/master' || startsWith( github.ref, 'refs/heads/release/' ) # Only runs on pushes
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - snyk
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - name: Download targets
        uses: actions/download-artifact@v3
        with:
          name: targets
      - name: Expand targets
        run: tar -xvzf targets.tar.gz
      - run: git fetch --tags
      - run: git status
      - name: Bump version and push tag
        id: tag-version
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          TAG_CONTEXT: branch
      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag-version.outputs.new_tag }}
          name: ${{ steps.tag-version.outputs.new_version }}
          body: ${{ steps.tag-version.outputs.changelog }}
      - run: git fetch --tags
      - name: publish
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_KEY }}
        run: sbt +publish
